version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: webapp:local
    volumes:
      - ./app:/data
    ports:
      - 3000:3000
    command: "npm start"
